/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /**
         * Start Project
         * @description Start a project from dropped BOQ files. Without a name, it is named after the first file.
         */
        post: operations["start_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Project */
        patch: operations["change_project_projects__project_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Sources
         * @description Add more BOQ files to a project. A file the project already has is ignored.
         */
        post: operations["add_sources_projects__project_id__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_projects__project_id__sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/sources/{source_id}/pages/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Page
         * @description A page's content. Sheets come a window of rows at a time, from row `start`.
         */
        get: operations["get_page_projects__project_id__sources__source_id__pages__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/sources/{source_id}/pages/{number}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Page Image
         * @description A PNG of a PDF page or an image; drawn once, then kept beside the page's content.
         */
        get: operations["page_image_projects__project_id__sources__source_id__pages__number__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work */
        get: operations["get_work_projects__project_id__work_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write
         * @description The engineer writes to the agent. A stopped or paused agent carries on.
         */
        post: operations["write_projects__project_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_projects__project_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_projects__project_id__decisions__decision_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description Items in use, in file order: all of them, one package's, or those not placed yet.
         */
        get: operations["list_items_projects__project_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Package */
        post: operations["create_package_projects__project_id__packages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Package
         * @description Remove a package; its items wait to be placed again.
         */
        delete: operations["remove_package_projects__project_id__packages__package_id__delete"];
        options?: never;
        head?: never;
        /** Change Package */
        patch: operations["change_package_projects__project_id__packages__package_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/packages/{package_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Packages
         * @description Merge other packages into this one; their items keep their placement reasons.
         */
        post: operations["merge_packages_projects__project_id__packages__package_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Place
         * @description The engineer puts items in a package. It settles any question the agent asked about them.
         */
        post: operations["place_projects__project_id__placements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global Rules
         * @description Rules the engineer chose to apply to every project.
         */
        get: operations["global_rules_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Forget Rule */
        delete: operations["forget_rule_rules__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Settings */
        patch: operations["change_settings_settings_patch"];
        trace?: never;
    };
    "/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** About */
        get: operations["about_about_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_ai_connections_get"];
        put?: never;
        /**
         * Add Connection
         * @description Keep a key only once it works. An OpenAI-compatible service may not list its models; for those, the model
         *     check proves the key.
         */
        post: operations["add_connection_ai_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Connection */
        delete: operations["remove_connection_ai_connections__connection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/connections/{connection_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_ai_connections__connection_id__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/connections/{connection_id}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Model */
        post: operations["check_model_ai_connections__connection_id__checks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIChoice */
        AIChoice: {
            /** Connection Id */
            connection_id: string;
            /** Model */
            model: string;
        };
        /** AboutOut */
        AboutOut: {
            /** Version */
            version: string;
            /** Data Folder */
            data_folder: string;
        };
        /**
         * Answer
         * @description The engineer's answer. Which fields count depends on the kind of decision.
         */
        Answer: {
            /** Approve */
            approve?: boolean | null;
            /** Relation */
            relation?: ("addition" | "replacement" | "revision") | null;
            /** Package Id */
            package_id?: string | null;
            /** Scope */
            scope?: ("item" | "project" | "all") | null;
            /** Choice */
            choice?: string | null;
            /** Note */
            note?: string | null;
        };
        /** Body_add_sources_projects__project_id__sources_post */
        Body_add_sources_projects__project_id__sources_post: {
            /** Files */
            files: string[];
        };
        /** Body_start_project_projects_post */
        Body_start_project_projects_post: {
            /** Files */
            files: string[];
            /** Name */
            name?: string | null;
        };
        /** CheckRequest */
        CheckRequest: {
            /** Model */
            model: string;
        };
        /** ConnectionCreate */
        ConnectionCreate: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "anthropic" | "openai" | "google" | "xai" | "openai_compatible";
            /** Api Key */
            api_key: string;
            /** Base Url */
            base_url?: string | null;
        };
        /** ConnectionOut */
        ConnectionOut: {
            /** Id */
            id: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "anthropic" | "openai" | "google" | "xai" | "openai_compatible";
            /** Label */
            label: string;
            /** Base Url */
            base_url: string | null;
            /** Key Hint */
            key_hint: string;
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["ModelCheck"];
            };
        };
        /** CoverageOut */
        CoverageOut: {
            /** Items */
            items: number;
            /** Placed */
            placed: number;
            /** Unplaced */
            unplaced: number;
            /** Waiting */
            waiting: number;
            /** Pages Left */
            pages_left: number;
            /** Pending Files */
            pending_files: number;
        };
        /**
         * DecisionOut
         * @description What the engineer is asked. Only the fields for its kind are set.
         */
        DecisionOut: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "consent" | "overlap" | "plan" | "uncertain" | "question" | "publish";
            /**
             * Raised By
             * @enum {string}
             */
            raised_by: "agent" | "tawreed";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Answered At */
            answered_at?: string | null;
            /** Answer */
            answer?: {
                [key: string]: unknown;
            } | null;
            /** Provider */
            provider?: string | null;
            /** Host */
            host?: string | null;
            /** File */
            file?: string | null;
            /** Earlier */
            earlier?: string | null;
            /** Share */
            share?: number | null;
            /** Recommended */
            recommended?: string | null;
            /** Packages */
            packages?: components["schemas"]["PlannedOut"][] | null;
            /** Removed */
            removed?: components["schemas"]["PackageRef"][] | null;
            /** Note */
            note?: string | null;
            item?: components["schemas"]["ItemOut"] | null;
            /** Candidates */
            candidates?: components["schemas"]["PackageRef"][] | null;
            /** Reason */
            reason?: string | null;
            /** Question */
            question?: string | null;
            /** Options */
            options?: string[] | null;
            /** Summary */
            summary?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageView */
        ImageView: {
            /**
             * Kind
             * @constant
             */
            kind: "image";
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** ItemOut */
        ItemOut: {
            /** Id */
            id: string;
            /** Ref */
            ref: number;
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Unit */
            unit: string;
            /** Quantity Text */
            quantity_text: string;
            /** Rate Text */
            rate_text: string;
            /** Amount Text */
            amount_text: string;
            /** Comment */
            comment: string;
            /** Headings */
            headings: string[];
            /** Source Id */
            source_id: string;
            /** File */
            file: string;
            /** Page */
            page: number;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /**
             * Origin
             * @enum {string}
             */
            origin: "cell" | "text" | "image";
            /** Verify */
            verify: boolean;
            /** Package Id */
            package_id: string | null;
            /** Decided By */
            decided_by: string | null;
        };
        /** ItemsPage */
        ItemsPage: {
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Total */
            total: number;
        };
        /** Merge */
        Merge: {
            /** Package Ids */
            package_ids: string[];
        };
        /** MessageIn */
        MessageIn: {
            /** Text */
            text: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: number;
            /**
             * Sender
             * @enum {string}
             */
            sender: "agent" | "engineer" | "tawreed";
            /** Text */
            text: string;
            /** Notice */
            notice: string | null;
            /** Params */
            params: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ModelCheck */
        ModelCheck: {
            /** Ok */
            ok: boolean;
            /** Problem */
            problem: string | null;
            /** Sees Images */
            sees_images: boolean;
            /** Checked At */
            checked_at: string;
        };
        /** PackageChange */
        PackageChange: {
            /** Name */
            name?: string | null;
            /** Scope */
            scope?: string | null;
        };
        /** PackageIn */
        PackageIn: {
            /** Name */
            name: string;
            /**
             * Scope
             * @default
             */
            scope: string;
        };
        /** PackageOut */
        PackageOut: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Scope */
            scope: string;
            /** Reason */
            reason: string;
            /** Items */
            items: number;
            /** Amount */
            amount: string;
            /** Without Amount */
            without_amount: number;
        };
        /** PackageRef */
        PackageRef: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** PageOut */
        PageOut: {
            /** Number */
            number: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "sheet" | "page" | "image";
            /** Name */
            name: string;
            /** Has Text */
            has_text: boolean;
            /** Hidden */
            hidden: boolean;
            /** Rows */
            rows: number | null;
            /** Cols */
            cols: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
        };
        /** Placement */
        Placement: {
            /** Item Ids */
            item_ids: string[];
            /** Package Id */
            package_id: string;
        };
        /** PlannedOut */
        PlannedOut: {
            /** Name */
            name: string;
            /** Scope */
            scope: string;
            /** Reason */
            reason: string;
            /** Keeps */
            keeps: components["schemas"]["PackageRef"][];
        };
        /** ProjectChange */
        ProjectChange: {
            /** Name */
            name: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Files */
            files: number;
        };
        /** RuleOut */
        RuleOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SettingsChange */
        SettingsChange: {
            /** Language */
            language?: ("en" | "ar") | null;
            /** Theme */
            theme?: ("system" | "light" | "dark") | null;
            ai?: components["schemas"]["AIChoice"] | null;
        };
        /** SettingsOut */
        SettingsOut: {
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "ar";
            /**
             * Theme
             * @enum {string}
             */
            theme: "system" | "light" | "dark";
            ai: components["schemas"]["AIChoice"] | null;
        };
        /** SheetView */
        SheetView: {
            /**
             * Kind
             * @constant
             */
            kind: "sheet";
            /** Name */
            name: string;
            /** First Row */
            first_row: number;
            /** Rows */
            rows: (string | number | boolean | null)[][];
            /** Total Rows */
            total_rows: number;
            /** Merged */
            merged: number[][];
        };
        /** SourceDetail */
        SourceDetail: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Size */
            size: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "spreadsheet" | "csv" | "pdf" | "image";
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "added" | "reading" | "read" | "failed";
            /** Problem */
            problem: string | null;
            /** Page Count */
            page_count: number;
            /** Pages */
            pages: components["schemas"]["PageOut"][];
        };
        /** SourceOut */
        SourceOut: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Size */
            size: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "spreadsheet" | "csv" | "pdf" | "image";
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "added" | "reading" | "read" | "failed";
            /** Problem */
            problem: string | null;
            /** Page Count */
            page_count: number;
        };
        /** TextLine */
        TextLine: {
            /** Top */
            top: number;
            /** Bottom */
            bottom: number;
            /** Text */
            text: string;
        };
        /** TextView */
        TextView: {
            /**
             * Kind
             * @constant
             */
            kind: "page";
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Lines */
            lines: components["schemas"]["TextLine"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkOut */
        WorkOut: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "read" | "plan" | "place" | "check" | "publish";
            /**
             * Agent
             * @enum {string}
             */
            agent: "working" | "idle" | "paused" | "no_ai";
            /** Decisions */
            decisions: components["schemas"]["DecisionOut"][];
            /** Answered */
            answered: components["schemas"]["DecisionOut"][];
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
            coverage: components["schemas"]["CoverageOut"];
            /** Packages */
            packages: components["schemas"]["PackageOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_project_projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_start_project_projects_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_project_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_sources_projects__project_id__sources_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_sources_projects__project_id__sources_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_projects__project_id__sources__source_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_projects__project_id__sources__source_id__pages__number__get: {
        parameters: {
            query?: {
                start?: number;
                count?: number;
            };
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
                source_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetView"] | components["schemas"]["TextView"] | components["schemas"]["ImageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_image_projects__project_id__sources__source_id__pages__number__image_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
                source_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_projects__project_id__work_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_projects__project_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_projects__project_id__stop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_projects__project_id__decisions__decision_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Answer"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_projects__project_id__items_get: {
        parameters: {
            query?: {
                package_id?: string | null;
                unplaced?: boolean;
                start?: number;
                count?: number;
            };
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_package_projects__project_id__packages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_package_projects__project_id__packages__package_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_package_projects__project_id__packages__package_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
                package_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_packages_projects__project_id__packages__package_id__merge_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
                package_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Merge"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_projects__project_id__placements_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Placement"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    global_rules_rules_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_rule_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_settings_settings_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    about_about_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AboutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_ai_connections_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_connection_ai_connections_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_connection_ai_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_ai_connections__connection_id__models_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_model_ai_connections__connection_id__checks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
