// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BootstrapInfo = { first_run: boolean, onboarding_required: boolean, onboarding_step: string, data_dir: string, has_api_key: boolean, has_compatible_key: boolean, has_gemini_key: boolean, has_grok_key: boolean, run_count: number, version: string, 
/**
 * "codex" | "anthropic" | "compatible" | "gemini" | "grok" | "none" — resolved AI provider for this session.
 */
provider: string, provider_preference: string, codex_installed: boolean, codex_authenticated: boolean, };
