// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClassificationMemoryEntry = { descriptionKey: string, packageCode: string, packageNameEn: string, packageNameAr: string, updatedAt: string, };
