// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInfo = { slug: string, display_name: string, description: string, default_reasoning_level: string | null, };
