// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RevisionReservation = { projectName: string, revision: number, revisionLabel: string, session: string, };
