// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RevisionOutput = { projectName: string, revision: number, revisionLabel: string, masterPath: string, packageFolder: string, revisionFolder: string, files: Array<string>, };
