// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateInfo = { current_version: string, latest_version: string, latest_tag: string, update_available: boolean, asset_name: string, asset_sha256: string | null, published_at: string | null, };
